function procResult = initProcResultStruct(type)

procResult = [];

switch lower(type)
case {'group','grp'}

    procResult = struct(...
                        'dodAvg',[],...
                        'dcAvg',[],...
                        'dodAvgStd',[],...
                        'dcAvgStd',[],...
                        'tHRF',[],...
                        'nTrials',[],...
                        'tInc',[],...
                        'grpAvgPass',[]...
                       );

case {'sess','session','subj','subject'}

    procResult = struct(...
                        'dodAvg',[],...
                        'dcAvg',[],...
                        'dodAvgStd',[],...
                        'dcAvgStd',[],...
                        'tHRF',[],...
                        'nTrials',[],...
                        'tInc',[],...
                        'SD',[]...
                       );
case {'run'}

    procResult = struct(...
                        'dod',[],...
                        'dc',[],...
                        'dodAvg',[],...
                        'dcAvg',[],...
                        'dodAvgStd',[],...
                        'dcAvgStd',[],...
                        'dodSum2',[],...
                        'dcSum2',[],...
                        'tHRF',[],...
                        'nTrials',[],...
                        'SD',[]...
                       );

end
