% When ever you change this function, then it is necessary to run
% genHelpProcStream() from the matlab command line

function callReg=procStreamReg()

callReg = ...
{...
'@ hmrIntensityNormalized dod (d',...
'@ hmrIntensity2OD dod (d',...
'@ hmrFlowInput dod (d',...
'@ enPCAFilter #[dod,svs,nSV] (dod,SD,tIncMan nSV %0.2f 0',...
'@ enPruneChannels SD (d,SD,tIncMan dRange %.0e_%.0e 1e4_1e7 SNRthresh %d 2 SDrange %.1f_%.1f 0_45 reset %d 0',...
'@ hmrMotionArtifact [tIncAuto] (dod,t,SD,tIncMan tMotion %0.1f 0.5 tMask %0.1f 1 STDEVthresh %0.1f 50 AMPthresh %0.2f 5',...
'@ hmrMotionArtifactByChannel [tIncAuto,tIncChAuto] (dod,t,SD,tIncMan tMotion %0.1f 0.5 tMask %0.1f 1 STDEVthresh %0.1f 50 AMPthresh %0.2f 5',...
'@ hmrMotionCorrectWavelet [dod] (dod,SD iqr %.1f 1.5 turn_on %d 1',...
'@ hmrMotionCorrectKurtosisWavelet [dod] (dod,SD kurt %.2f 3.3',...
'@ hmrMotionCorrectPCA #[dod,svsMotion,nSVMotion] (SD,dod,tIncAuto nSV %.2f .8',...
'@ hmrMotionCorrectPCArecurse [dod,tIncAuto,svsmc,nSVmc,tIncAuto0] (dod,t,SD,tIncMan tMotion %0.1f 0.5 tMask %0.1f 1.0 STDEVthresh %0.1f 20.0 AMPthresh %0.2f 5 nSV %.2f 0.97 maxIter %d 5 turnon %d 1',...
'@ hmrMotionCorrectPCArecurse_Ch_dual [dod,tIncAuto,svsmc,nSVmc,tIncAuto0] (dod,t,SD,tIncMan tMotion %0.1f 0.5 tMask %0.1f 1.0 STDEVthresh %0.1f 20.0 AMPthresh %0.2f 5 nSV %.2f 0.97 maxIter %d 5 turnon %d 1',...
'@ hmrMotionCorrectPCArecurseCh_SG [dod,tIncAuto,svsmc,nSVmc,tIncAuto0] (dod,t,SD,tIncMan nSV %.2f 0.97 maxIter %d 3 FrameSize_sec %d 10 turnon %d 1',...
'@ hmrMotionCorrectSpline [dod] (dod,t,SD,tIncChAuto p %.2f .99 turnon %d 1',...
'@ hmrMotionCorrectSplineSG [dod] (dod,d,t,SD p %.2f .99 FrameSize_sec %d 10 turn_on %d 1',...
'@ hmrMotionCorrectCbsi [dc] (dc,SD turnon %d 1',...
'@ hmrMotionCorrectRLOESS [dod] (dod,t span %.2f 0.02 turnon %d 1',...
'@ hmrMotionCorrectSG [dod] (dod,t FrameSize_sec %d 10 turn_on %d 1',...
'@ enStimRejection [s,tRangeStimReject] (t,s,tIncAuto,tIncMan tRange %0.1f_%0.1f -5_10',...
'@ hmrBandpassFilt dod (dod,t hpf %0.3f 0.01 lpf %0.2f 0.5',...
'@ hmrBandpassFiltConc dc (dc,t hpf %0.3f 0.01 lpf %0.2f 0.5',...
'@ enPCAFilter #[dod,svs_dod,nSV_dod] (dod,SD,tIncMan nSV %0.2f_%0.2f 0_0',...
'@ hmrOD2Conc dc (dod,SD ppf %0.1f_%0.1f 6_6',...
'@ hmrConc2OD dod (dc,SD ppf %0.1f_%0.1f 6_6',...
'@ enPCAFilter #[dc,svs,nSV] (dc,SD,tIncMan nSV %0.1f_%0.1f 0_0',...
'@ enCrossCorrelation #[cc,ml,cc_thresh] (SD,dc cc_thresh %0.2f 0.4',...
'@ enAdaptiveFilteringSS [dc,iNearestSS] (SD,t,dc nTimePts %d 1 Step_Size  %0.1e 1e-4',...
'@ enStimIncData_varargin [s,nFuncParam0,funcParam0,funcParamFormat0,funcParamVal0] (s,t,userdata *',...
'@ hmrCreateAuxRegressor Aaux (aux,t param %d_%.3f_%.1f 1_0_1',...
'@ hmrBlockAvg [dcAvg,dcAvgStd,tHRF,nTrials,dcSum2] (dc,s,t trange %0.1f_%0.1f -2_20',...
'@ hmrBlockAvg [dodAvg,dodAvgStd,tHRF,nTrials,dodSum2] (dod,s,t trange %0.1f_%0.1f -2_20'...
'@ hmrBlockAvg [dcAvg,dcAvgStd,tHRF,nTrials,dcSum2,dcTrials] (dc,s,t trange %0.1f_%0.1f -2_20',...
'@ plotTrials #[dcTrials,tHRF,SD] (dcTrials,tHRF,SD',...
'@ hmrFindHrfOutlier [s,dcAvg,dcAvgStd,nTrials,dcSum2,dcTrials] (s,tHRF,dcTrials tRange %0.1f_%0.1f 4_8 stdThresh %.1f 3 minNtrials %d 0',...
'@ hmrRegressors [dcResid,dcAvg,tHRF,nTrials] (dc,s,t trange %0.1f_%0.1f -2_10',...
'@ hmrDeconvTB_3rd [dcAvg,dcAvgStd,tHRF,nTrials,dcSum2] (dc,s,t,Aaux trange %0.1f_%0.1f -2_10 gstd %0.1f 1 gms %0.1f 1',...
'@ hmrDeconvTB_SS3rd [dodAvg,dodAvgStd,tHRF,nTrials,dod,dodResid,dodSum2] (dod,s,t,SD,Aaux trange %0.1f_%0.1f -2_10 gstd %0.1f 1 gms %0.1f 1 rhoSD_ssThresh %0.1f 15 ',...
'@ hmrDeconvTB_SS3rd [dcAvg,dcAvgStd,tHRF,nTrials,dc,dcResid,dcSum2] (dc,s,t,SD,Aaux trange %0.1f_%0.1f -2_10 gstd %0.1f 1 gms %0.1f 1 rhoSD_ssThresh %0.1f 15 ',...
'@ hmrDeconvTB_SS3rd_Highest [dcAvg,dcAvgStd,tHRF,nTrials,dc,dcResid,dcSum2] (dc,s,t,SD,cc,Aaux trange %0.1f_%0.1f -2_10 gstd %0.1f 1 gms %0.1f 1 rhoSD_ssThresh %0.1f 15',...
'@ hmrDeconv_SS [dc] (dc,t,SD'...
'@ hmrImageHrfMeanTwin [dodAvgImg] (dodAvg,tHRF trange %0.1f_%0.1f 5_10'...
'@ hmrImageHrfMeanTwin [dcAvgImg] (dcAvg,tHRF trange %0.1f_%0.1f 5_10'...
'@ hmrImageRecon img (SD,dodAvgImg,dodResid alpha %.1e 1e-3'...
'@ hmrDeconvHRF_Drift [dcAvg,dcAvgStd,tHRF,nTrials,dc,dcResid,dcSum2] (dc,s,t,Aaux,tIncAuto trange %0.1f_%0.1f -2_10 idxBasis %d 2 paramsBasis %0.1f_%0.1f_%0.1f_%0.1f_%0.1f_%0.1f 0.1_3.0_10.0_1.8_3.0_10.0  driftOrder %d 3 flagMotionCorrect %d 0 ',...
'@ hmrDeconvHRF_DriftSS [dcAvg,dcAvgStd,tHRF,nTrials,dc,dcResid,dcSum2,beta,R] (dc,s,t,SD,Aaux,tIncAuto trange %0.1f_%0.1f -2_10 glmSolveMethod %d 1 idxBasis %d 2 paramsBasis %0.1f_%0.1f_%0.1f_%0.1f_%0.1f_%0.1f 0.1_3.0_10.0_1.8_3.0_10.0  rhoSD_ssThresh %0.1f 15 flagSSmethod %d 1 driftOrder %d 3 flagMotionCorrect %d 0 ',...
};